//
// Created by Robin Ellingsen on 2022-04-08.
//

#ifndef ARDUINO_CPP_CHECKHARDWARESTATECHANGE_H
#define ARDUINO_CPP_CHECKHARDWARESTATECHANGE_H

void checkHardwareStateChange();

#endif //ARDUINO_CPP_CHECKHARDWARESTATECHANGE_H
